### ISSUE TITLE
兄弟, 你把那个求数据的 issue 关了.  我也想要一份数据

### ISSUE THREAD

**Issue by ume-technology** [menghuanlater/Tianchi2020ChineseMedicineNER#5]
时间有点久了, 不知道 XD 你还有没有数据了, 有的话我求一份原始的 txt 和 .ann 文件.  拜托了.

**Comment by ume-technology** [comment]
swhardbewell@qq.com

**Comment by ume-technology** [comment]
因为一些其它事情的原因,  涉及到一些 NER 的问题,  求一份数据, 拜托了.

**Comment by menghuanlater** [comment]
稍等哈，我待会去实验室给你发



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月05日 13:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [menghuanlater/Tianchi2020ChineseMedicineNER] 兄弟, 你把那个求数据的 issue 关了.  我也想要一份数据 (Issue #5) |

因为一些其它事情的原因, 涉及到一些 NER 的问题, 求一份数据, 拜托了.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ume-technology** [comment]
哇~　　谢谢兄弟

**Comment by menghuanlater** [comment]
已发至QQ邮箱


| |
安林
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月5日 ***@***.***> 写道：

哇~　　谢谢兄弟

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
